"""Observed OpenAPI annotations, independent of operation execution.

Fields and evidence follow the phase-2 source inventory. Statuses and envelopes
were reconciled with controllers and the REST baseline in phase 5. This module
does not read documentary JSON at runtime or claim closed response schemas.
It never supplies validation rules to the compatibility dispatcher.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ObservedOperation:
    fields: tuple[str, ...]
    statuses: tuple[int, ...]
    input_policy: str
    input_notes: str
    response_notes: str
    evidence: tuple[str, ...]
    effect: str
    command_failure_codes: bool


OBSERVED_OPERATIONS: dict[tuple[str, str], ObservedOperation] = {
    ('GET', '/api/status'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK + uptime_seconds, uptime_str, health, rx_count, tx_count, error_count, timestamp',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/system_controller.py:get_status'),
        'pasivo',
        False,
    ),
    ('GET', '/api/health'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data health',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/system_controller.py:get_health'),
        'pasivo',
        False,
    ),
    ('GET', '/api/diagnostics'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data health, mismo get_health',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/system_controller.py:get_health'),
        'pasivo',
        False,
    ),
    ('GET', '/api/preflight'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna; checker toma configuración host',
        '200 OK data reporte de run_all_async o thread; no traduce fallos de checks a status HTTP',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/system_controller.py:run_preflight'),
        'red/serial/chequeos locales según PreflightChecker',
        False,
    ),
    ('GET', '/api/diagnostics/report.md'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query_parsed_unused',
        'ignora limit/offset una vez parseados',
        '200 OK markdown,text iguales; fallback texto no disponible',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/logs_controller.py:route_logs', 'src/web/controllers/logs_controller.py:_handle_diagnostics_report'),
        'local',
        False,
    ),
    ('GET', '/api/diagnostics/report'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query_parsed_unused',
        'igual report.md',
        '200 OK markdown,text',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/logs_controller.py:route_logs', 'src/web/controllers/logs_controller.py:_handle_diagnostics_report'),
        'local',
        False,
    ),
    ('GET', '/api/diagnostics/export'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data bundle si DiagnosticManager; sin manager 200 {status:error,message:"No diagnostics"}',
        ('src/web/api_router.py:_dispatch_system',),
        'local',
        False,
    ),
    ('GET', '/api/system/logs'): ObservedOperation(
        ('limit', 'offset', 'level', 'search'),
        (200,),
        'logs_raw_query',
        'query limit=100, sólo isdigit; level/search primer valor, offset parseado pero no usado',
        '200 OK data[],count,counters{errors,warnings,info,debug},current_level,total_logs',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/logs_controller.py:route_logs', 'src/web/controllers/logs_controller.py:_handle_system_logs'),
        'pasivo',
        False,
    ),
    ('DELETE', '/api/system/logs'): ObservedOperation(
        (),
        (204,),
        'router_merged',
        'ninguna',
        '204 vacío, limpia deque/handler',
        ('src/web/api_router.py:_dispatch_system', 'src/web/controllers/system_controller.py:clear_logs'),
        'local',
        False,
    ),
    ('GET', '/api/system/logs/level'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK level; fallback INFO',
        ('src/web/api_router.py:_dispatch_system',),
        'pasivo',
        False,
    ),
    ('POST', '/api/system/logs/level'): ObservedOperation(
        ('level',),
        (200, 400),
        'router_merged',
        'level=INFO convertido str',
        '200 OK level;400 invalid_log_level o diagnostic_unavailable',
        ('src/web/api_router.py:_dispatch_system',),
        'local',
        False,
    ),
    ('GET', '/api/nodes'): ObservedOperation(
        ('limit', 'offset'),
        (200, 400),
        'router_merged',
        'limit100 [1..500],offset0 [0..100000], int acotado',
        '200 OK data[],count,total_count,limit,offset;400 parámetros',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:list_nodes'),
        'pasivo',
        False,
    ),
    ('GET', '/api/lqi'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data[],count; fallback[]',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:get_lqi'),
        'pasivo',
        False,
    ),
    ('GET', '/api/analytics'): ObservedOperation(
        ('range',),
        (200,),
        'router_merged',
        'range=str(value), default24h; controlador no enumera rechazo',
        '200 OK data summary/enriquecimientos',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:get_analytics'),
        'pasivo',
        False,
    ),
    ('POST', '/api/analytics/reset'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK message,data resultado reset',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:reset_metrics'),
        'local',
        False,
    ),
    ('DELETE', '/api/analytics/reset'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'igual POST',
        '200 OK message,data',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:reset_metrics'),
        'local',
        False,
    ),
    ('GET', '/api/rf/heatmap'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data{points[],count}; descarta lat/lon inválida y0,0',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:get_rf_heatmap'),
        'pasivo',
        False,
    ),
    ('GET', '/api/airtime/stats'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data tracker; fallback hourly_used_ms0,hourly_budget_ms36000,hourly_duty_cycle_pct0',
        ('src/web/api_router.py:_dispatch_nodes', 'src/web/controllers/nodes_controller.py:get_airtime_stats'),
        'pasivo',
        False,
    ),
    ('GET', '/api/rf/noise'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data.matrix[] {pubkey,name,role,noise_floor_dbm,snr,rssi,channel(default0),freq(default915)}',
        ('src/web/api_router.py:_dispatch_nodes',),
        'pasivo',
        False,
    ),
    ('GET', '/api/contacts'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna, sin paginación',
        '200 OK data client_contacts[],count',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_handle_contacts_route'),
        'pasivo',
        False,
    ),
    ('POST', '/api/contacts'): ObservedOperation(
        ('public_key', 'key', 'name', 'alias', 'role', 'is_favorite', 'latitude', 'lat', 'adv_lat', 'longitude', 'lon', 'adv_lon'),
        (200, 201, 400, 422, 500, 503),
        'router_merged',
        'esquema C abajo',
        '201 nuevo /200 existente OK data contact.to_dict;400/422 validación;CF;500 persistence_failed',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_create_or_update_contact', 'src/web/controllers/contacts_controller.py:_contact_validation'),
        'serial+disco',
        True,
    ),
    ('DELETE', '/api/contacts'): ObservedOperation(
        ('public_key', 'key'),
        (204, 400, 404, 422, 500, 503),
        'router_merged',
        'public_key > key > vacío, str.strip.lower',
        '204;400 cannot_delete_local_station;404 contact_not_found;CF;500 persistence_failed',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_delete_contact', 'src/web/controllers/contacts_controller.py:_handle_contacts_route'),
        'serial+disco',
        True,
    ),
    ('DELETE', '/api/contacts/{public_key}'): ObservedOperation(
        ('public_key', 'key'),
        (204, 400, 404, 422, 500, 503),
        'router_merged',
        'regex exactamente64 hex, minúscula; **body/query public_key/key puede reemplazar clave path**',
        'mismos status DELETE root; key path inválida⇒404 route_not_found',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_delete_contact', 'src/web/controllers/contacts_controller.py:_handle_contacts_route'),
        'serial+disco',
        True,
    ),
    ('POST', '/api/contacts/sync'): ObservedOperation(
        (),
        (200, 503),
        'router_merged',
        'ninguna',
        '200 OK imported,data client_contacts[],count;503 transceiver_offline/sync_failed',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_sync_contacts'),
        'serial lectura tabla +registro/disco',
        False,
    ),
    ('POST', '/api/contacts/share'): ObservedOperation(
        ('public_key', 'key'),
        (200, 400, 422, 503),
        'router_merged',
        'public_key > key, str.strip; faltante400 missing_public_key',
        '200 OK result;CF',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_share_contact'),
        'RF share_contact',
        True,
    ),
    ('GET', '/api/contacts/export'): ObservedOperation(
        ('public_key', 'pubkey', 'key', 'name', 'alias'),
        (200, 400, 422),
        'router_merged',
        'public_key OR pubkey OR key; name OR alias si no registro',
        '200 OK uri,qr_uri,message_tag,data,result;400 missing_public_key;422/400 validation C',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_export_contact', 'src/web/controllers/contacts_controller.py:_contact_validation'),
        'serial export local opcional',
        False,
    ),
    ('POST', '/api/contacts/export'): ObservedOperation(
        ('public_key', 'pubkey', 'key', 'name', 'alias'),
        (200, 400, 422),
        'router_merged',
        'igual GET',
        'mismos status/envelope',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_export_contact', 'src/web/controllers/contacts_controller.py:_contact_validation'),
        'serial',
        False,
    ),
    ('POST', '/api/contacts/import'): ObservedOperation(
        ('public_key', 'key', 'name', 'alias', 'role', 'is_favorite', 'latitude', 'lat', 'adv_lat', 'longitude', 'lon', 'adv_lon', 'pubkey', 'contacts', 'data', 'payload', 'uri'),
        (200, 201, 400, 422, 500, 503),
        'router_merged',
        'esquema I abajo',
        '201 OK imported,data[]; rama binaria200 OK result;400/422/CF/500',
        ('src/web/api_router.py:_dispatch_contacts', 'src/web/controllers/contacts_controller.py:_import_contact', 'src/web/controllers/contacts_controller.py:_contact_validation'),
        'serial+disco',
        True,
    ),
    ('GET', '/api/contacts/discovered'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data{discovered[],count}',
        ('src/web/api_router.py:_dispatch_contacts',),
        'pasivo',
        False,
    ),
    ('POST', '/api/contacts/accept'): ObservedOperation(
        ('public_key', 'target_node'),
        (200, 400),
        'router_merged',
        'public_key > target_node, str.strip',
        '400 missing_public_key;200 {status:ok\\|error,accepted:bool}, incluso false',
        ('src/web/api_router.py:_dispatch_contacts',),
        'registro accept_discovered_contact',
        False,
    ),
    ('GET', '/api/channels'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna; sync_serial=False',
        '200 OK data[] enmascarados,count',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_get_channels', 'src/web/controllers/channels_controller.py:_handle_channels_route'),
        'pasivo',
        False,
    ),
    ('POST', '/api/channels'): ObservedOperation(
        ('index', 'overwrite', 'name', 'psk'),
        (200, 201, 400, 409, 422, 500, 503),
        'router_merged',
        'index1 entero estricto, name defaultCanal N, psk vacío, overwrite to_bool false',
        '201 nuevo/200 overwrite OK data enmascarada;400 index fuera;409 channel_already_exists;422 índice/nombre;CF;500 global save',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_create_or_update_channel'),
        'serial+disco',
        True,
    ),
    ('DELETE', '/api/channels'): ObservedOperation(
        ('index',),
        (204, 400, 404, 422, 500, 503),
        'router_merged',
        'index0 entero estricto',
        '204;422 invalid_channel_index;400 cannot_delete_public_channel;404 channel_not_found;CF;500 global',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_delete_channel'),
        'serial delete_channel o set_channel vacío',
        True,
    ),
    ('POST', '/api/channels/sync'): ObservedOperation(
        (),
        (200, 503),
        'router_merged',
        'ninguna',
        '200 OK data[] enmascarados,count;503 sync_failed',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_sync_channels'),
        'serial lectura',
        False,
    ),
    ('GET', '/api/channels/export'): ObservedOperation(
        ('index',),
        (200, 400, 404),
        'router_merged',
        'index=int(default0), aquí bool/float admitidos por int',
        '200 OK uri,qr_uri,data{type,index,name,secret,is_encrypted,is_public};400 invalid_channel_index/cannot_export_public_channel;404 channel_not_found',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_export_channel'),
        'local',
        False,
    ),
    ('POST', '/api/channels/export'): ObservedOperation(
        ('index',),
        (200, 400, 404),
        'router_merged',
        'igual GET',
        'mismos status',
        ('src/web/api_router.py:_dispatch_channels', 'src/web/controllers/channels_controller.py:_export_channel'),
        'local',
        False,
    ),
    ('POST', '/api/tx'): ObservedOperation(
        ('text', 'to', 'target', 'channel_index', 'channel_idx', 'request_id'),
        (200, 400, 408, 422, 429, 503),
        'router_merged',
        'text=str().strip obligatorio; destino to si existe, si no target; channel_index > channel_idx default0 vía int; request_id defaultweb_<ms>',
        '200 OK data resultado;400/422 validación;408 tx_timeout;429/503 tx_submission_failed;CF',
        ('src/web/api_router.py:_dispatch_tx', 'src/web/controllers/tx_controller.py:send_tx'),
        'RF cola NORMAL submit y espera hasta30s',
        True,
    ),
    ('GET', '/api/messages/recent'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna; no paginación',
        '200 OK data[] todos recent_messages,count',
        ('src/web/api_router.py:_dispatch_tx', 'src/web/controllers/tx_controller.py:get_recent_messages'),
        'pasivo',
        False,
    ),
    ('POST', '/api/admin'): ObservedOperation(
        ('action', 'command', 'cmd', 'request_id', 'id', 'target_node', 'repeater', 'params'),
        (200, 400, 422, 503),
        'router_merged',
        'diccionario completo a handle_admin; action sólo leído para log',
        '200 OK result,response,message (dos textos de result.result OR result.message); validación delegada',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:execute_admin_command', 'src/admin_handler.py:_handle'),
        'serial/RF/MQTT según acción',
        True,
    ),
    ('POST', '/api/admin/repeater'): ObservedOperation(
        ('target_node', 'repeater', 'action', 'command', 'params', 'password', 'request_id'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater str.strip; action > command defaultstats-radio str; params={},password="",request_id defaultweb_rep_<s>',
        '400 missing_target_node;200 OK data',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:execute_repeater_command'),
        'RF remoto',
        True,
    ),
    ('POST', '/api/repeater/remote/login'): ObservedOperation(
        ('target_node', 'repeater', 'password'),
        (200, 400, 401, 422, 503),
        'router_merged',
        'target_node > repeater; password str excepto null⇒vacío; no trim password',
        '400 missing_target_node/empty_password;401 auth_failed con data;200 OK data autenticado',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:login'),
        'RF login',
        True,
    ),
    ('POST', '/api/repeater/remote/logout'): ObservedOperation(
        ('target_node', 'repeater'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater',
        '400 missing_target_node;200 OK data',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:logout'),
        'RF logout',
        True,
    ),
    ('POST', '/api/repeater/remote/config'): ObservedOperation(
        ('target_node', 'repeater', 'password', 'params'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater; password null⇒vacío/string; params default{}',
        '400 missing_target_node;200 OK data, action=remote_repeater_set_config',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:set_remote_config'),
        'RF configuración',
        True,
    ),
    ('POST', '/api/repeater/remote/action'): ObservedOperation(
        ('target_node', 'repeater', 'action', 'password', 'params'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater; action str.strip;password como config;params{}',
        '400 missing_fields;200 OK data',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:execute_remote_action'),
        'RF acción',
        True,
    ),
    ('POST', '/api/repeater/remote/neighbours'): ObservedOperation(
        ('target_node', 'repeater', 'count', 'offset', 'password'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater;count255,offset0,password"" sin coerción de esos3 en controller',
        '400 missing_target_node;200 OK data;action=req_neighbours',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:get_neighbours'),
        'RF consulta',
        True,
    ),
    ('POST', '/api/repeater/remote/owner'): ObservedOperation(
        ('target_node', 'repeater', 'password'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater;password""',
        '400 missing_target_node;200 OK data;action=req_owner',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:get_owner'),
        'RF consulta',
        True,
    ),
    ('POST', '/api/repeater/remote/regions'): ObservedOperation(
        ('target_node', 'repeater', 'password'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater;password""',
        '400 missing_target_node;200 OK data;action=req_regions',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:get_regions'),
        'RF consulta',
        True,
    ),
    ('POST', '/api/repeater/remote/clock'): ObservedOperation(
        ('target_node', 'repeater', 'password'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater;password""',
        '400 missing_target_node;200 OK data;action=req_clock',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:get_clock'),
        'RF consulta',
        True,
    ),
    ('POST', '/api/repeater/remote/acl'): ObservedOperation(
        ('target_node', 'repeater', 'password'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater;password""',
        '400 missing_target_node;200 OK data;action=req_acl',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:get_acl'),
        'RF consulta',
        True,
    ),
    ('POST', '/api/node/ping_zero'): ObservedOperation(
        ('target_node', 'repeater', 'target'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > repeater > target, str.strip',
        '400 missing_target_node;200 OK data',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:ping_zero'),
        'RF ping',
        True,
    ),
    ('POST', '/api/repeater/ping_zero'): ObservedOperation(
        ('target_node', 'repeater', 'target'),
        (200, 400, 422, 503),
        'router_merged',
        'igual node/ping_zero',
        'igual',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:ping_zero'),
        'RF ping',
        True,
    ),
    ('POST', '/api/traceroute'): ObservedOperation(
        ('target_node', 'target', 'repeater', 'to'),
        (200, 400, 422, 503),
        'router_merged',
        'target_node > target > repeater > to, str.strip',
        '400 missing_target_node;200 OK data',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:traceroute'),
        'RF trace',
        True,
    ),
    ('POST', '/api/repeater/traceroute'): ObservedOperation(
        ('target_node', 'target', 'repeater', 'to'),
        (200, 400, 422, 503),
        'router_merged',
        'igual traceroute',
        'igual',
        ('src/web/api_router.py:_dispatch_repeater', 'src/web/controllers/repeater_controller.py:traceroute'),
        'RF trace',
        True,
    ),
    ('GET', '/api/config'): ObservedOperation(
        ('refresh',),
        (200,),
        'router_merged',
        'refresh false',
        '200 OK data config enriquecida/redactada;get_device_config:22',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_device_config'),
        'pasivo o serial refresh',
        False,
    ),
    ('POST', '/api/config'): ObservedOperation(
        ('adv_loc_policy', 'af', 'airtime_cutoff_enabled', 'airtime_cutoff_resume_pct', 'airtime_cutoff_threshold_pct', 'airtime_factor', 'bandwidth', 'bw', 'coding_rate', 'cr', 'custom_vars', 'devicepin', 'duty_cycle_limit_pct', 'frequency', 'lat', 'latitude', 'lon', 'longitude', 'manual_add_contacts', 'multi_acks', 'name', 'path_hash_mode', 'pin', 'power', 'radio_freq', 'repeat', 'repeat_enabled', 'repeater_pre_send_delay_enabled', 'repeater_pre_send_delay_s', 'rx_delay', 'rx_dly', 'sf', 'spreading_factor', 'telemetry_mode_base', 'telemetry_mode_env', 'telemetry_mode_loc', 'tx_power', 'warn_threshold_pct'),
        (200, 400, 422, 503),
        'router_merged',
        'diccionario parámetros LC abajo',
        '200 OK data redactada;422 invalid_parameter/CF;set_local_config:113',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_local_config', 'src/admin/local_config_executor.py:_prevalidate_local_params'),
        'serial+host/disco/RF según parámetro',
        True,
    ),
    ('GET', '/api/config/radio'): ObservedOperation(
        ('refresh',),
        (200,),
        'router_merged',
        'refresh false',
        'igual GET config',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_device_config'),
        'pasivo/serial',
        False,
    ),
    ('POST', '/api/config/radio'): ObservedOperation(
        ('adv_loc_policy', 'af', 'airtime_cutoff_enabled', 'airtime_cutoff_resume_pct', 'airtime_cutoff_threshold_pct', 'airtime_factor', 'bandwidth', 'bw', 'coding_rate', 'cr', 'custom_vars', 'devicepin', 'duty_cycle_limit_pct', 'frequency', 'lat', 'latitude', 'lon', 'longitude', 'manual_add_contacts', 'multi_acks', 'name', 'path_hash_mode', 'pin', 'power', 'radio_freq', 'repeat', 'repeat_enabled', 'repeater_pre_send_delay_enabled', 'repeater_pre_send_delay_s', 'rx_delay', 'rx_dly', 'sf', 'spreading_factor', 'telemetry_mode_base', 'telemetry_mode_env', 'telemetry_mode_loc', 'tx_power', 'warn_threshold_pct'),
        (200, 400, 422, 503),
        'router_merged',
        'igual POST config, no subset impuesto',
        'igual POST config',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_local_config', 'src/admin/local_config_executor.py:_prevalidate_local_params'),
        'serial/modifica radio',
        True,
    ),
    ('GET', '/api/config/identity'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ignora refresh, get_device_config()',
        '200 OK data config completa redactada',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_device_config'),
        'pasivo',
        False,
    ),
    ('POST', '/api/config/identity'): ObservedOperation(
        ('adv_loc_policy', 'af', 'airtime_cutoff_enabled', 'airtime_cutoff_resume_pct', 'airtime_cutoff_threshold_pct', 'airtime_factor', 'bandwidth', 'bw', 'coding_rate', 'cr', 'custom_vars', 'devicepin', 'duty_cycle_limit_pct', 'frequency', 'lat', 'latitude', 'lon', 'longitude', 'manual_add_contacts', 'multi_acks', 'name', 'path_hash_mode', 'pin', 'power', 'radio_freq', 'repeat', 'repeat_enabled', 'repeater_pre_send_delay_enabled', 'repeater_pre_send_delay_s', 'rx_delay', 'rx_dly', 'sf', 'spreading_factor', 'telemetry_mode_base', 'telemetry_mode_env', 'telemetry_mode_loc', 'tx_power', 'warn_threshold_pct'),
        (200, 400, 422, 503),
        'router_merged',
        'igual POST config, no subset impuesto',
        'igual POST config',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_local_config', 'src/admin/local_config_executor.py:_prevalidate_local_params'),
        'serial',
        True,
    ),
    ('GET', '/api/config/custom_vars'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK custom_vars,data iguales;admin ausente{};get_custom_vars:290',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_custom_vars'),
        'serial si admin disponible',
        False,
    ),
    ('POST', '/api/config/custom_vars'): ObservedOperation(
        ('key', 'value', 'val', 'vars'),
        (200, 400, 422, 503),
        'router_merged',
        'key/value(val fallback) OR vars dict no vacío;KV str/null⇒"";separadores : , NUL CR LF prohibidos',
        '200 OK custom_vars,data fresh;400 invalid_schema;422 empty_key/invalid_vars_object/empty_key_in_vars/invalid_custom_var;503 admin_unavailable;CF;set_custom_vars:299',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_custom_vars'),
        'serial',
        True,
    ),
    ('DELETE', '/api/config/custom_vars'): ObservedOperation(
        ('key',),
        (200, 400, 422, 503),
        'router_merged',
        'key str,trim',
        '200 OK custom_vars,data;400 missing_key;503 admin_unavailable;CF;delete_custom_var:358',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:delete_custom_var'),
        'serial',
        True,
    ),
    ('GET', '/api/config/path_hash_mode'): ObservedOperation(
        (),
        (200, 503),
        'router_merged',
        'ninguna',
        '200 OK path_hash_mode,data{path_hash_mode};503 admin_unavailable/read_unconfirmed;get:374',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_path_hash_mode'),
        'serial',
        False,
    ),
    ('POST', '/api/config/path_hash_mode'): ObservedOperation(
        ('mode', 'path_hash_mode'),
        (200, 400, 422, 503),
        'router_merged',
        'mode > path_hash_mode requerido;int o string trim0/1/2;bool/float prohibidos',
        '200 OK path_hash_mode,data resultado;422 invalid_mode;503 admin_unavailable;CF;set:385',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_path_hash_mode'),
        'serial',
        True,
    ),
    ('GET', '/api/config/autoadd'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK autoadd_config,data iguales;fallback{};get:410',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_autoadd_config'),
        'serial',
        False,
    ),
    ('POST', '/api/config/autoadd'): ObservedOperation(
        ('flags', 'config', 'autoadd', 'max_hops'),
        (200, 400, 422, 503),
        'router_merged',
        'flags > config > autoadd default0;max_hops opcional;int/string signed digits SIN trim;bool/float prohibidos;flags0..255,hops0..64',
        '200 OK data;422 invalid_flags/invalid_max_hops/invalid_autoadd o unsupported_parameter con código delegado;503 admin_unavailable;CF;set:416',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_autoadd_config'),
        'serial',
        True,
    ),
    ('GET', '/api/config/flood_scope'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK flood_scope,data iguales;fallback{};get:460',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:get_flood_scope'),
        'serial',
        False,
    ),
    ('POST', '/api/config/flood_scope'): ObservedOperation(
        ('scope', 'scope_name'),
        (200, 400, 422, 503),
        'router_merged',
        'scope > scope_name;null/string;global */0/global/none permitidos;otra string prefijo#≤30bytes y sin control',
        '200 OK data;422 invalid_scope;503 admin_unavailable;CF;set:466',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:set_flood_scope'),
        'serial',
        True,
    ),
    ('POST', '/api/node/advert'): ObservedOperation(
        ('flood',),
        (200, 400, 422, 503),
        'router_merged',
        'flood to_bool false',
        '200 OK data;400 admin_handler_unavailable;CF;broadcast_advert:183',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:broadcast_advert'),
        'RF advert hop0/flood',
        True,
    ),
    ('POST', '/api/node/reboot'): ObservedOperation(
        (),
        (200, 400, 422, 503),
        'router_merged',
        'ninguna',
        '200 OK data;CF;reboot_local:280',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:reboot_local'),
        'serial reinicio',
        True,
    ),
    ('POST', '/api/config/sync-clock'): ObservedOperation(
        ('epoch', 'timestamp'),
        (200, 400, 422, 503),
        'router_merged',
        'epoch > timestamp;ausente/null⇒hora host;int positivo ostring signed trim;bool/float prohibidos',
        '200 OK data;422 invalid_epoch;503 admin_handler_unavailable;CF;sync_clock:197',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:sync_clock'),
        'serial RTC',
        True,
    ),
    ('POST', '/api/config/clear-stats'): ObservedOperation(
        (),
        (200, 400, 422, 503),
        'router_merged',
        'ninguna',
        '200 OK data;503 admin_handler_unavailable;CF;clear_stats:218',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:clear_stats'),
        'serial+contadores host',
        True,
    ),
    ('GET', '/api/config/refresh'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna;refresh forzado',
        '200 OK data;refresh_hardware_config:248',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:refresh_hardware_config'),
        'serial',
        False,
    ),
    ('POST', '/api/config/refresh'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'igual GET',
        'igual GET',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:refresh_hardware_config'),
        'serial',
        False,
    ),
    ('POST', '/api/config/reconnect'): ObservedOperation(
        (),
        (200, 400, 422, 500, 503),
        'router_merged',
        'ninguna',
        '200 OK message si reconnect serial,200 OK data fallbackadmin;503 serial_reconnect_failed;500 {status:error,message} para excepción reconnect;CF;reconnect_serial:259',
        ('src/web/api_router.py:_dispatch_config', 'src/web/controllers/config_controller.py:reconnect_serial'),
        'serial reapertura',
        True,
    ),
    ('GET', '/api/services/config'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data configuración redactada +external_mqtt_connected',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:get_services_config'),
        'pasivo/disco fallbackload',
        False,
    ),
    ('POST', '/api/services/config'): ObservedOperation(
        ('external_mqtt', 'local_mqtt', 'tcp_server'),
        (200, 400, 422, 500),
        'router_merged',
        'objeto; external_mqtt/local_mqtt/tcp_server parciales',
        '200 OK message,reloaded,data redactada;400 invalid_json;422 invalid_host/invalid_port/invalid_transport/invalid_auth_type/invalid_location_privacy;500 reload_failed',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:set_services_config'),
        'red+disco,hotreload',
        False,
    ),
    ('GET', '/api/services/presets'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK presets =get_services_config.data.all_presets',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:get_services_config'),
        'pasivo',
        False,
    ),
    ('POST', '/api/services/presets'): ObservedOperation(
        ('name', 'host', 'port', 'id', 'description', 'transport', 'tls_enabled', 'tls_verify', 'auth_type', 'username', 'password', 'token', 'downlink_enabled', 'location_privacy', 'topic_mode', 'topic_prefix', 'region_iata', 'payload_format', 'filter_observer_mode', 'filter_public', 'filter_channels', 'filter_direct', 'filter_telemetry', 'filter_nodes', 'filter_raw', 'keepalive', 'qos'),
        (200, 400, 422, 500),
        'router_merged',
        'presets S abajo',
        '200 OK message,preset redactado;422 missing_name/missing_host/invalid_port;400 system_preset_protected;500 bridge_unavailable/global',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:save_preset'),
        'local+disco',
        False,
    ),
    ('DELETE', '/api/services/presets/{id:path}'): ObservedOperation(
        (),
        (200, 400, 404, 500),
        'router_merged',
        'todo suffix tras prefijo, .strip, admite slash interno',
        '200 OK message;400 system_preset_protected;404 preset_not_found;500 bridge_unavailable/global',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:delete_preset'),
        'local+disco',
        False,
    ),
    ('POST', '/api/services/mqtt-external/test'): ObservedOperation(
        ('host', 'port', 'transport', 'tls_enabled', 'tls_verify', 'auth_type', 'username', 'password', 'token', 'timeout'),
        (200, 400, 422, 500),
        'router_merged',
        'host requerido;port1883 int1..65535;credenciales+tls/transport/auth;timeoutfloat(value OR5) clamp1..10',
        '200 {status:ok\\|error,data:test_result} según data.ok;400 invalid_json;422 missing_host/invalid_port;500 global conversión/ejecución',
        ('src/web/api_router.py:_dispatch_services', 'src/web/controllers/services_controller.py:test_external_mqtt'),
        'red conexión efímera MQTT',
        False,
    ),
    ('GET', '/api/packets'): ObservedOperation(
        ('limit', 'offset', 'direction', 'type', 'order'),
        (200, 400, 503),
        'router_merged',
        'limit100[1..500],offset0[0..100000];direction/type str default"";order str asc odesc',
        '200 OK data[],count,total_count,limit,offset,order,session_id,capture_enabled;400 coerción/bounds/invalid_order;503 packet_buffer_unavailable',
        ('src/web/api_router.py:_dispatch_packets', 'src/web/controllers/packets_controller.py:get_packets'),
        'pasivo',
        False,
    ),
    ('DELETE', '/api/packets'): ObservedOperation(
        (),
        (204,),
        'router_merged',
        'ninguna',
        '204 aun sin buffer',
        ('src/web/api_router.py:_dispatch_packets', 'src/web/controllers/packets_controller.py:clear_packets'),
        'local',
        False,
    ),
    ('GET', '/api/packets/export'): ObservedOperation(
        ('format',),
        (200, 503),
        'router_merged',
        'format str lower defaultjson, controllerstrip;pcap/csv especiales, cualquier otro⇒json',
        '200 OK format,filename,mime_type,size_bytes +base64_data PCAP otext_data JSON/CSV;503 packet_buffer_unavailable',
        ('src/web/api_router.py:_dispatch_packets', 'src/web/controllers/packets_controller.py:export_packets'),
        'local',
        False,
    ),
    ('GET', '/api/map/status'): ObservedOperation(
        (),
        (200,),
        'router_merged',
        'ninguna',
        '200 OK data status map',
        ('src/web/api_router.py:_dispatch_misc',),
        'local',
        False,
    ),
    ('POST', '/api/map/reload'): ObservedOperation(
        (),
        (200, 500),
        'router_merged',
        'ninguna',
        '200 OK message,data status map;500 map_reload_failed',
        ('src/web/api_router.py:_dispatch_misc',),
        'local reindex/disco/thread',
        False,
    ),
    ('GET', '/api/messages'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query',
        'sólo query limit100/offset0,primer valor,isDigit;sin rango/techo;inválido⇒default',
        '200 OK data[],count,total_count,limit,offset',
        ('src/web/api_router.py:_dispatch_misc', 'src/web/controllers/logs_controller.py:route_logs'),
        'pasivo deque200',
        False,
    ),
    ('GET', '/api/telemetry'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query',
        'igual messages',
        '200 OK data[],count,total_count,limit,offset',
        ('src/web/api_router.py:_dispatch_misc', 'src/web/controllers/logs_controller.py:route_logs'),
        'pasivo deque200',
        False,
    ),
    ('GET', '/api/logs/download'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query_parsed_unused',
        'ninguna (limit/offset parseados no usados)',
        '200 OK raw_logs,log_file,line_count',
        ('src/web/api_router.py:_dispatch_misc', 'src/web/controllers/logs_controller.py:route_logs', 'src/web/controllers/logs_controller.py:_handle_raw_logs_download'),
        'local tail2000 líneas o deque fallback',
        False,
    ),
    ('GET', '/api/logs/raw'): ObservedOperation(
        ('limit', 'offset'),
        (200,),
        'logs_raw_query_parsed_unused',
        'igual download',
        'igual download',
        ('src/web/api_router.py:_dispatch_misc', 'src/web/controllers/logs_controller.py:route_logs', 'src/web/controllers/logs_controller.py:_handle_raw_logs_download'),
        'local',
        False,
    ),
}
